/// Flutter icons CoolUI
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CoolUI
///      fonts:
///       - asset: fonts/CoolUI.ttf
///
/// 
///
part of cool_ui;

class CoolUIIcons {
  CoolUIIcons._();

  static const _kFontFam = 'CoolUIIcons';

  static const IconData success_no_circle = const IconData(0xea08, fontFamily: _kFontFam,fontPackage: "cool_ui");
}
