/// Flutter icons CoolUIExample
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CoolUIExample
///      fonts:
///       - asset: fonts/CoolUIExample.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CoolUIExampleIcon {
  CoolUIExampleIcon._();

  static const _kFontFam = 'CoolUIExample';

  static const IconData popover = const IconData(0xe801, fontFamily: _kFontFam);
}
